apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-wz9if91dln0fcjafpl8v6
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  labels:
    component: mysql
  name: mysql
  namespace: component-mysql
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: port-mysql
      nodePort: 31306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    component: mysql
  sessionAffinity: None
  type: LoadBalancer
