apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  creationTimestamp: '2020-03-04T03:17:56Z'
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: mysql
  name: mysql
  resourceVersion: '311479282'
  selfLink: /api/v1/persistentvolumes/mysql
  uid: be54c20f-5dc6-11ea-92e3-b6068211400b
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pvc
    namespace: component-mysql
    resourceVersion: '311479280'
    uid: 7b32088e-5dc7-11ea-aff0-662473e6d21e
  flexVolume:
    driver: alicloud/nas
    options:
      mode: '777'
      modeType: non-recursive
      path: /k8s/mysql
      server: 2ac784b08f-wqp63.cn-shenzhen.nas.aliyuncs.com
      vers: '3'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql
  volumeMode: Filesystem
status:
  phase: Bound
