apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-wz9if91dln0fcjafpl8v6
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  labels:
    app: rabbitmq
    type: LoadBalancer
  name: rabbitmq
  namespace: component-rabbitmq
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 30672
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: amqp
      nodePort: 31672
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: LoadBalancer
