---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: connector-nb
  namespace: siglife-cloud
spec:
  selector:
    matchLabels:
      service: connector-nb
  replicas: 2
  template:
    metadata:
      labels:
        service: connector-nb
    spec:
      imagePullSecrets:
        - name: siglife-docker-registry
      containers:
        - name: connector-nb
          image: nexus.sigsmart.com.cn:8001/cloudv3/connector-nb:3.1.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: siglife-nb-config
          ports:
            - containerPort: 8095
            - containerPort: 7650

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: service-nb
  name: service-nb
  namespace: siglife-cloud
spec:
  selector:
    service: connector-nb
  ports:
    - name: port-http
      port: 80
      protocol: TCP
      targetPort: 8095
    - name: port-udp
      port: 7650
      protocol: UDP
      targetPort: 7650