apiVersion: v1
kind: Namespace
metadata:
  name: component-redis
  labels:
    app.kubernetes.io/name: component
    app.kubernetes.io/part-of: component

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: component-redis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500M
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.199.237
    path: /root/nfs/data/redis/pv0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: component-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
  storageClassName: nfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: component-redis
spec:
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /var/lib/redis
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: redis
  name: redis
  namespace: component-redis
spec:
  type: NodePort
  ports:
    - name: port-redis
      port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 31379
  selector:
    component: redis