spring:
  datasource:
    url: jdbc:mysql://192.168.199.237:31306/iam_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver


  rabbitmq:
    host: 192.168.199.238
    username: root
    password: root@123
    port: 32672

  user:
    addr: nanjing
    name: chen
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.entity
