spring:
  datasource:
    url: jdbc:mysql://192.168.199.240:3306/crz_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql@456$%^
    driver-class-name: com.mysql.cj.jdbc.Driver


  rabbitmq:
    host: 192.168.199.240
    username: root
    password: root@123

  user:
    addr: nanjing
    name: chen
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.entity
