apiVersion: v1
kind: Namespace
metadata:
  name: component-emqx
  labels:
    app.kubernetes.io/name: component
    app.kubernetes.io/part-of: component

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: component-emqx
spec:
  selector:
    matchLabels:
      component: emqx
  replicas: 1
  template:
    metadata:
      labels:
        component: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:latest
          ports:
            - containerPort: 8883  #mqtt:ssl not exposed
            - containerPort: 1883  #mqtt:tcp
            - containerPort: 18083  #http:dashboard
            - containerPort: 8080  #http:management not exposed
            - containerPort: 8083  #mqtt:ws
            - containerPort: 8084  #mqtt:wss not exposed

---
#this service build for nginx-ingress,see ingress-nginx/ConfigMap/tcp-services
apiVersion: v1
kind: Service
metadata:
  labels:
    component: emqx
  name: emqx-tcp-ws
  namespace: component-emqx
spec:
  type: NodePort
  selector:
    component: emqx
  ports:
    - name: port-tcp
      port: 1883
      protocol: TCP
      targetPort: 1883
      nodePort: 31083
    - name: port-ws
      port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 31085
---
# this service build for users to access emqx dashboard
apiVersion: v1
kind: Service
metadata:
  labels:
    component: emqx
  name: emqx-dashboard
  namespace: component-emqx
spec:
  type: NodePort
  ports:
    - name: port-dashboard
      port: 18083
      protocol: TCP
      targetPort: 18083
      nodePort: 30083
  selector:
    component: emqx