apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  creationTimestamp: '2020-03-09T03:17:28Z'
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: redis-ha0
  name: redis-ha0
  resourceVersion: '341749157'
  selfLink: /api/v1/persistentvolumes/redis-ha0
  uid: 81e6a723-61b4-11ea-aff0-662473e6d21e
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-redis-ha-default-server-0
    namespace: component-redis
    resourceVersion: '341744684'
    uid: 6a440fc7-61b4-11ea-92e3-b6068211400b
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /k8s/redisha/0
      server: 2ac784b08f-wqp63.cn-shenzhen.nas.aliyuncs.com
      vers: '3'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-ha
  volumeMode: Filesystem
status:
  phase: Bound
