apiVersion: v1
kind: Namespace
metadata:
  name: component-nginx
  labels:
    app.kubernetes.io/name: component
    app.kubernetes.io/part-of: component

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: component-nginx
spec:
  accessModes:
    - ReadWriteMany        #访问模式定义为只能以读写的方式挂载到单个节点
  capacity:
    storage: 100M
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.199.237
    path: /root/nfs/data/nginx


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: component-nginx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  storageClassName: nfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: component-nginx
spec:
  selector:
    matchLabels:
      component: nginx
  replicas: 2
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 7650
            - containerPort: 7651
            - containerPort: 7653
            - containerPort: 8090
            - containerPort: 8091
            - containerPort: 18083
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /etc/nginx
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-pvc

---
kind: Service
apiVersion: v1
metadata:
  namespace: component-nginx
  name: nginx
  labels:
    component: nginx
    type: LoadBalancer
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: nb-udp
      protocol: UDP
      port: 7650
      targetPort: 7650
      nodePort: 31650
    - name: mqtts-balance
      protocol: TCP
      port: 7651
      targetPort: 7651
      nodePort: 31651
    - name: mqtts-bus
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 31090
    - name: mqtt-balance
      protocol: TCP
      port: 7653
      targetPort: 7653
      nodePort: 31653
    - name: mqtt-bus
      protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 31091
  selector:
    component: nginx