---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: connector-dtang
  namespace: siglife-cloud
spec:
  selector:
    matchLabels:
      service: connector-dtang
  replicas: 2
  template:
    metadata:
      labels:
        service: connector-dtang
    spec:
      imagePullSecrets:
        - name: siglife-docker-registry
      containers:
        - name: connector-dtang
          image: nexus.sigsmart.com.cn:8001/cloudv3/connector-dtang:3.1.0-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: siglife-dtang-config
          ports:
            - containerPort: 8097

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: connector-dtang
  name: connector-dtang
  namespace: siglife-cloud
spec:
  selector:
    service: connector-dtang
  ports:
    - name: port-1
      port: 80
      protocol: TCP
      targetPort: 8097