{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "redis-cluster.serviceAccountName" . }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
{{- end -}}
