apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-cluster.fullname" . }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{ include "common.tplvalues.render" ( dict "value" .Values.service.labels "context" $ ) | indent 4 }}
    {{- end -}}
{{- if .Values.service.annotations }}
  annotations: {{ include "common.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: {{ .Values.service.port }}
      targetPort: tcp-redis
  selector: {{- include "redis-cluster.matchLabels" $ | nindent 4 }}
