{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "redis-cluster.fullname" . }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "redis-cluster.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "redis-cluster.serviceAccountName" . }}
{{- end -}}
