{{- if and .Values.usePassword (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis-cluster.fullname" . }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ include "redis-cluster.password" . | b64enc | quote }}
{{- end -}}
