{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ $.Values.mysql.namespace }}
data:
  my.cnf: |-
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    #log-error      = /var/log/mysql/error.log
    # By default we only accept connections from localhost
    #bind-address   = 127.0.0.1
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    #sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    max_connections=1000
    max_connect_errors=10000

---
apiVersion: v1
kind: Service
metadata:
{{- if eq $.Values.environment "ali" }}
  annotations:
{{- range $key, $value := $.Values.aliLoadBalancerPublicParam }}
    {{ $key }}: "{{ $value }}"
{{- end }}
{{ end }}
  labels:
    component: mysql
  name: {{ $.Values.mysql.serviceName }}
  namespace: {{ $.Values.mysql.namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: port-mysql
      nodePort: {{ $.Values.mysql.nodePort }}
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    component: mysql
  sessionAffinity: None
{{- if eq $.Values.environment "ali" }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ $.Values.mysql.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ $.Values.mysql.namespace }}
spec:
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root@123
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: config-volume
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
{{- end }}